server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/biblioteca?sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework: WARN
  file:
    name: logs/biblioteca-prod.log
